name: pastebin
description: A pure Dart Pastebin API Wrapper.
version: 0.0.2
homepage: https://github.com/saiive/pastebin.dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.1
  dartz:  ^0.9.2
  xml: 
  meta: ^1.2.3

dev_dependencies:
  effective_dart: 
  test: 
  mockito: